### ISSUE TITLE
Redesign new style of mappool card

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#11]
大家好啊，我是说的道理。今天来点大家想看的评论啊。

- [x] Basic layout implementation
- [x] Animation and interaction
- [ ] Tests

**Comment by NaughtyChas** [comment]
Mappool scene will not be used during OFFC tournament, add this feature if wanted. Lowering down priority to level 3.

**Comment by NaughtyChas** [comment]
Mappool scene is currently not in a fine state, as we have went too far on the Board scene, something went broke in the visuals of the mappool scene. Because of that, entry of the mappool screen might get removed in the future.

Since we have no requirements to support this feature in the code at this stage, closing this issue now.

**Comment by CloneWith** [comment]
As a goal in the long term, decided to reopen this and plan for this week.

**Comment by NaughtyChas** [comment]
Might be useful to provide a quick reference to protection visual in osu!mania 4K match, `MWC4K`:

![image](https://github.com/user-attachments/assets/2c23013b-5ad1-49d0-a341-10fbc4b6a1bd)

I reckon putting the icon on the right side might be a better choice, or, we design a brand new visual scheme, more about this can be progressed on figma, depending on your decision.

**Comment by CloneWith** [comment]
> Might be useful to provide a quick reference to protection visual in osu!mania 4K match, `MWC4K`:
> 
> ![image](https://private-user-images.githubusercontent.com/57820700/371852066-2c23013b-5ad1-49d0-a341-10fbc4b6a1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MjM1ODYsIm5iZiI6MTcyNzYyMzI4NiwicGF0aCI6Ii81NzgyMDcwMC8zNzE4NTIwNjYtMmMyMzAxM2ItNWFkMS00OWQwLWEzNDEtMTBmYmM0YjZhMWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDE1MjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MDYwMTM2OGZlNTQxNjkyYTZhZDlhNzFiNDY5Mzc4NTYyMTY5MjFmZjQwMDQ1ZTBkYWMxZDg5ZDg0YzUwZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tgZ9TMAJ3vVR-HUcS_x2Bzz5Mp4_28m2FVW9kd3raO8)
> 
> I reckon putting the icon on the right side might be a better choice, or, we design a brand new visual scheme, more about this can be progressed on figma, depending on your decision.

I'm pretty into this. Would you work on this further? Can redesign this with tool (Figma, or 即时设计 more generally used here) assisted when possible.

**Comment by NaughtyChas** [comment]
> > Might be useful to provide a quick reference to protection visual in osu!mania 4K match, `MWC4K`:
> > ![image](https://private-user-images.githubusercontent.com/57820700/371852066-2c23013b-5ad1-49d0-a341-10fbc4b6a1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MjM1ODYsIm5iZiI6MTcyNzYyMzI4NiwicGF0aCI6Ii81NzgyMDcwMC8zNzE4NTIwNjYtMmMyMzAxM2ItNWFkMS00OWQwLWEzNDEtMTBmYmM0YjZhMWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDE1MjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MDYwMTM2OGZlNTQxNjkyYTZhZDlhNzFiNDY5Mzc4NTYyMTY5MjFmZjQwMDQ1ZTBkYWMxZDg5ZDg0YzUwZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tgZ9TMAJ3vVR-HUcS_x2Bzz5Mp4_28m2FVW9kd3raO8)
> > I reckon putting the icon on the right side might be a better choice, or, we design a brand new visual scheme, more about this can be progressed on figma, depending on your decision.
> 
> I'm pretty into this. Would you work on this further? Can redesign this with tool (Figma, or 即时设计 more generally used here) assisted when possible.

Not sure if Figma is accessible and running stable under Mainland China network?

**Comment by NaughtyChas** [comment]
I've come up with a new set of design of the mappool scene components. Majority of the assets are from osu! official figma design library,so it should be looking good when fitting into lazer interface.

https://www.figma.com/design/W5gXDLnX0ZbkTRNZSW9iAy/Mappool-design?m=auto&t=TklghI1kCb8Z6Jzo-1

Only components design are being displayed. More stuff (animation design, detail polishing) will get updated later.

**Comment by CloneWith** [comment]
Just've listed some critical tasks for tracking, written above.
Happy coding!

**Comment by NaughtyChas** [comment]
Nah bro we didn't finished the tests.
