### ISSUE TITLE
New Board view layout

### ISSUE THREAD

**Issue by CloneWith** [CloneWith/osu#12]

**Comment by NaughtyChas** [comment]
We have to also change the layout of this screen to match the requirement of the art & design team. See draft below:

![image](https://github.com/user-attachments/assets/9d1d9b54-1589-4b94-b7c4-55af6d267e89)

Please note that we have to add almost the same layout for EX screen to, more of it will be traced in issue #4 .

**Comment by NaughtyChas** [comment]
Visual design for `UserListPanel` has updated, see in [this issue](https://github.com/CloneWith/osu/issues/14#issuecomment-2262486402)

**Comment by NaughtyChas** [comment]
Closing this issue. We have created a final stable version of the Board view so far.
