### ISSUE TITLE
Bugged display on icons in `Board`

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#16]
This bug can be reproduced by assign box status, and use right click to clear status of the box when box is "*flashing*".

A white icon will be left on box even though there is no assigned status. This icon cannot be removed by right click again.

When a box has complete its "flashing" animation, using right click to clear status will remove the icon as we expected.

**Comment by CloneWith** [comment]
As was talked yesterday, after clearing the transform process of these elements, this issue should be resolved as well.

**Comment by NaughtyChas** [comment]
> As was talked yesterday, after clearing the transform process of these elements, this issue should be resolved as well.

Tested and reviewed. Closing this issue as the bug has been succesfully patched.
