### ISSUE TITLE
Automatic EX & winning situation judgement

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#17]
This should be possible after commit [bc3507f](https://github.com/CloneWith/osu/commit/bc3507fcd8fd2a3d0ce17bd8e67e95a59ddb557a).

- [x] EX situation judgement
- [x] Winning situation judgement
- [x] ~Special visual effects~ (*not planned*)

**Comment by NaughtyChas** [comment]
> * [ ]  Special visual effects

We have used `InstructionDisplay` to display EX situation, and we have also used `EX Indicator` at the right panel to indicate that. Closing this checkbox and closing this issue now? Pinging @CloneWith for more reaction.

You may use emojis to react this comment.

**Comment by CloneWith** [comment]
> Closing this checkbox and closing this issue now?

Don't have much idea for this special effect, seemingly we don't need that so much, and this issue can be closed.
