### ISSUE TITLE
Bugged display of `InstructionDisplay`

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#18]
![image](https://github.com/user-attachments/assets/728a1f3f-b352-41cd-83d5-116f12df4e3b)
![V@6O_MO($Z} 671CXL%X40_tmb](https://github.com/user-attachments/assets/e1a6a34a-fbc8-4e5e-975e-bba43d873b64)

**Comment by cdwcgt** [comment]
应该借由 https://github.com/CloneWith/osu/pull/23 解决了
