### ISSUE TITLE
New design for boxes in Board & EX scene

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#20]
Seems that the text inside the boxes are making the board screen seems too complex, several changes can be taken into account:

- [x] Remove artist from title
- [x] Add text truncate effect (...) to the title
- [x] Remove "mapper", `Beatmap?.Metadata.Author.Username` and "difficulty" text.
  - *In other words, leave `Beatmap?.DifficultyName` only*.

Probably have to extend these design into EX screen?

---

Adding `DifficultyIcon` to EX screen would be a lot better:

- [x] Add `DifficultyIcon` to EX screen

|*without* `DifficultyIcon`|*with* `DifficultyIcon`|
|:-:|:-:|
|![image](https://github.com/user-attachments/assets/6263a194-f483-4325-b414-b93d3ab45254)|![image](https://github.com/user-attachments/assets/5bc33221-4c53-4a16-b904-a4d170a65119)|

- [x] Add animation to `DifficultyIcon`

**Comment by NaughtyChas** [comment]
> * [x]  Remove artist from title
> * [x]  Add text truncate effect (...) to the title
> * [x]  Remove "mapper", `Beatmap?.Metadata.Author.Username` and "difficulty" text.

commit [9460514](https://github.com/CloneWith/osu/commit/946051477d8a68a6c96fc12457218d4ba0651f83) solve these three tasks at once:

![image](https://github.com/user-attachments/assets/8642a2ce-8c35-4b7d-8972-c489cbd60ed9)

We have to apply the same display scheme to EX screen.

**Comment by NaughtyChas** [comment]
> * [ ]  Add `DifficultyIcon` to EX screen

Commit [cc9f688](https://github.com/CloneWith/osu/commit/cc9f6885b95e7f2d2e19dfcac6e3802f7a6b76bc) added these `StarRatingDisplay` to EX screen:

![image](https://github.com/user-attachments/assets/f077e19b-c827-429e-9cb8-7f1518b730ea)

**Comment by CloneWith** [comment]
> Considering adding animation by setting `bool animated = true`.

Have just tried this, but there doesn't seem to be any visible animation.

Does the animation play upon load? I think this is highly possible.

**Comment by NaughtyChas** [comment]
> > Considering adding animation by setting `bool animated = true`.
> 
> Have just tried this, but there doesn't seem to be any visible animation.
> 
> Does the animation play upon load? I think this is highly possible.

I believe that the animation has to set with correct parameters. See file `StarRatingDisplay.cs`:

```csharp
        protected override void LoadComplete()
        {
            base.LoadComplete();

            Current.BindValueChanged(c =>
            {
                if (animated)
                    this.TransformBindableTo(displayedStars, c.NewValue.Stars, 750, Easing.OutQuint);
                else
                    displayedStars.Value = c.NewValue.Stars;
            });

            // other content
        }

```

...if `animated` is true, it animates the transition of `displayedStars` to the new value over 750 milliseconds using the Easing.OutQuint easing function. Might be crucial to define suitable values for these parameters. 

Might be possible to set the animation using this approach?

```csharp
// Initialize with 0.00 star rating
starRatingDisplay = new StarRatingDisplay(new StarDifficulty(0, 0), StarRatingDisplaySize.Regular, true)

// Update the star rating to the actual value, triggering the animation.
starRatingDisplay.Current.Value = new StarDifficulty(Beatmap?.StarRating ?? 0, 0);
```


If we have set the correct parameters, it should play animation play upon load I suppose. There is a high chance where the animation has already loaded before we switch into EX Screen.

Maybe we can considering the use of `TournamentSceneManager.cs`, when `EXBoardScreen` is active, display that animation.

**Comment by NaughtyChas** [comment]
Animation will not being considered, now we can close this issue.
