### ISSUE TITLE
Code Quality Assurance

### ISSUE THREAD

**Issue by cdwcgt** [CloneWith/osu#24]
idk when
maybe finish

**Comment by CloneWith** [comment]
tai true le bro

**Comment by NaughtyChas** [comment]
This will be taken into account when all the major features have complete their development process

**Comment by CloneWith** [comment]
Since we've cleaned up our code recently, this issue is going to be closed.
Still, this issue persists as a long term principle. We'd rather remember this when we start coding at the very first time.

**Comment by cdwcgt** [comment]
快进到自己都看不懂
![hoshizora_tetsudou_to_shiro_no_tabi_by_listder_sticker_bot_agadt](https://github.com/user-attachments/assets/1f731263-f541-4f7c-91e4-943fe9eabd57)
