### ISSUE TITLE
Wrong display on rank

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#27]
As you can see:

![image](https://github.com/user-attachments/assets/6aa4c103-c0e8-42c3-bfbe-bb871213be64)

Displayed rank is not being standarized to osu!standard.

**Comment by NaughtyChas** [comment]
Will carry out a test soon.

**Comment by NaughtyChas** [comment]
![image](https://github.com/user-attachments/assets/7648c6ec-cac3-4e37-86d2-0fa362d3cda4)

Looks like this issue can be drawn to its conclusion. The strange color issue (caused by chat) can be found at #30 .

**Comment by CloneWith** [comment]
我要飞了
![Manba out](https://github.com/user-attachments/assets/737eca0f-b724-4c9b-a6a1-9eba2b7b3c1b)
