### ISSUE TITLE
Display issue on chat

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#30]
![image](https://github.com/user-attachments/assets/c7338522-f49b-4769-9007-9d94fe81c1c5)

Can be recreated by:

- Use a bracket setting and enter Board / EX Scene
- Select another bracket
- Return to Board / EX Scene

*Particularly when switching to "Bracket Reset" with team OTTO inside, other brackets looks fine.*

**Comment by CloneWith** [comment]
Is it possible to add a loading icon to the Chat Container? Depends.

**Comment by NaughtyChas** [comment]
Probably caused by chatBox transitioning effect, which I believe that this effect was added in a commit.
Consider to remove it if we have to find a fix.

**Comment by CloneWith** [comment]
> Probably caused by chatBox transitioning effect, which I believe that this effect was added in a commit. Consider to remove it if we have to find a fix.

Good afternoon NKs. I'm Short Dolly 🤓
Please make me apologize that CloneWith isn't here now, and I'll miyushuodedaoli
Glad to tell u that it's actually something about ppy's hair number, which exceeds the maximum limit of signed integer. We are going to manba him out 🌿 because some tricky cases made us on fire yesterday, the Crazy Thursday, as well as some weird naming principles.
It should be fixed in subsequent committttttttttttttttttttttttttttttttttttttttttttttttttttttKernel..Panic......StackOverflow....................
为了你，我变成狼人模样
我在佛前苦苦♂f\*\*k♂了几千遍
大家好啊，我是元神今天来点大家不想看的东西啊
每次都想装作很倔强 但是界面都缴械投降
孩子们 我要飞了乐乐乐

**Comment by CloneWith** [comment]
> > Probably caused by chatBox transitioning effect, which I believe that this effect was added in a commit. Consider to remove it if we have to find a fix.
> 
> Good afternoon NKs. I'm Short Dolly 🤓 Please make me apologize that CloneWith isn't here now, and I'll miyushuodedaoli ♿♿♿ Glad to tell u that it's actually something about ppy's hair number, which exceeds the maximum limit of signed integer. We are going to manba him out 🌿 because some tricky cases made us on fire yesterday, the Crazy 📣 Thursday, as well as some weird naming principles. It should be fixed in subsequent committttttttttttttttttttttttttttttttttttttttttttttttttttttKernel..Panic......StackOverflow.................... 为了你，我变成狼人模样 我在佛前苦苦♂f**k♂了几千遍 大家好啊，我是元神今天来点大家不想看的东西啊 每次都想装作很倔强 但是界面都缴械投降 孩子们 我要飞了乐乐乐 韭菜盒子 贼几把好吃 可老好吃了👍

Resolved in this comment, 乐

**Comment by NaughtyChas** [comment]
> > > Probably caused by chatBox transitioning effect, which I believe that this effect was added in a commit. Consider to remove it if we have to find a fix.
> > 
> > 
> > Good afternoon NKs. I'm Short Dolly 🤓 Please make me apologize that CloneWith isn't here now, and I'll miyushuodedaoli ♿♿♿ Glad to tell u that it's actually something about ppy's hair number, which exceeds the maximum limit of signed integer. We are going to manba him out 🌿 because some tricky cases made us on fire yesterday, the Crazy 📣 Thursday, as well as some weird naming principles. It should be fixed in subsequent committttttttttttttttttttttttttttttttttttttttttttttttttttttKernel..Panic......StackOverflow.................... 为了你，我变成狼人模样 我在佛前苦苦♂f**k♂了几千遍 大家好啊，我是元神今天来点大家不想看的东西啊 每次都想装作很倔强 但是界面都缴械投降 孩子们 我要飞了乐乐乐 韭菜盒子 贼几把好吃 可老好吃了👍
> 
> Resolved in this comment, 乐

Bro just resolved this issue by writing shitposts and Otto, more Otto, more Otto, more Otto.
