### ISSUE TITLE
New EX view layout

### ISSUE THREAD

**Issue by CloneWith** [CloneWith/osu#4]
Todo:

- [x] Filter for `EX` mod maps
- [x] Mod Icon aligning
- [x] Main layout

**Comment by NaughtyChas** [comment]
Mentioned in issue #5, we have to add a similar layout to EX screen to with design draft:

![image](https://github.com/user-attachments/assets/49f6fa72-5ead-4603-99fc-9b014a6f115d)

Please note that the art&design team have asked to try the vertical arrangement of the EX maps, it is possible to change to our original design if that looks ugly.

**Comment by CloneWith** [comment]
After briefly checking, everything here goes fine I think, should we close this issue now?

**Comment by NaughtyChas** [comment]
> After briefly checking, everything here goes fine I think, should we close this issue now?

Agreed, closing this...
