### ISSUE TITLE
Add IRC chat display in Board scene

### ISSUE THREAD

**Issue by CloneWith** [CloneWith/osu#5]
Have implemented a simple layout with the Chat display at the left side of the Board.

Further work needs to be done to:

- [x] Add IRC chat display in board scene
- [x] Move the round title somewhere else
- [x] Validation
- [x] Add rounded corner visual style for IRC chat board. (*Appended*)
- [ ] Revert chatbox visual style

**Comment by NaughtyChas** [comment]
> * [ ]  Validation

Further information required for "Validation".

**Comment by NaughtyChas** [comment]
> * [ ]  Add rounded corner visual style for IRC chat board. (_Appended_)

Maybe worth considering to add this visual style for better looking.

**Comment by CloneWith** [comment]
> Further information required for "Validation".

Since I didnt have a channel to display in the Chat section, it might be good to let you have a look at the changes. If everything seems okay then we could safely check this off the list.

**Comment by NaughtyChas** [comment]
> > Further information required for "Validation".
> 
> Since I didnt have a channel to display in the Chat section, it might be good to let you have a look at the changes. If everything seems okay then we could safely check this off the list.

Chatbox is working as expected, checked this off:

![image](https://github.com/user-attachments/assets/eb579054-05ec-4d3c-814c-bbf88aaa09c7)

**Comment by CloneWith** [comment]
> Maybe worth considering to add this visual style for better looking.

Just added a round corner of 10(px?) in the latest commit, and accidentally pushed to your branch ;w;
Anyway you can try it at your side...

**Comment by NaughtyChas** [comment]
> > Maybe worth considering to add this visual style for better looking.
> 
> Just added a round corner of 10(px?) in the latest commit, and accidentally pushed to your branch ;w; Anyway you can try it at your side...

Reviewed.

**Comment by NaughtyChas** [comment]
> * [ ]  Move the round title somewhere else


See commit [72f4385](https://github.com/CloneWith/osu/commit/72f438538257bd2457bcae7ce2a0e95dc999c32e). 

We have to use the same chatbox layout in EX Scene, more about this will be traced in a new issue.

**Comment by NaughtyChas** [comment]
latest release of osu!(lazer) in release [2024.731.0](https://github.com/ppy/osu/releases/tag/2024.731.0) has [changed the visual for chat boxes](https://github.com/ppy/osu/pull/29137):

![image](https://github.com/user-attachments/assets/42079321-a210-47d1-94a4-dd7fb91dbedf)

Careful when syncing main branch if we don't want this new visual style.

**Comment by CloneWith** [comment]
> Careful when syncing main branch if we don't want this new visual style.

thx for noticing me about this! 

Our group definitely won't want this I think.

I'll try to find out if there is a reachable variable controlling this behaviour.

**Comment by CloneWith** [comment]
> I'll try to find out if there is a reachable variable controlling this behaviour.

Fortunately the contributor kindly used a public struct, enabling us to simply change this argument on message line definition:

```csharp
        protected partial class MatchMessage : StandAloneMessage
        {
            public MatchMessage(Message message, LadderInfo info)
                : base(message)
            {
                // Disable alternating background
                AlternatingBackground = false;

                if (info.CurrentMatch.Value is TournamentMatch match)
                {
                    if (match.Team1.Value?.Players.Any(u => u.OnlineID == Message.Sender.OnlineID) == true)
                        UsernameColour = TournamentGame.COLOUR_RED;
                    else if (match.Team2.Value?.Players.Any(u => u.OnlineID == Message.Sender.OnlineID) == true)
                        UsernameColour = TournamentGame.COLOUR_BLUE;
                }
            }
        }
```

**Comment by NaughtyChas** [comment]
In commit [47feaad](https://github.com/CloneWith/osu/commit/47feaad8f5e142441ff494fdeac0c16b4ec8f9ed) I have disabled that `AlternatingBackground` effect for chatboxes. Apart from that, some details are worth notice:

|Before release [2024.731.0](https://github.com/ppy/osu/releases/tag/2024.731.0)|After release [2024.731.0](https://github.com/ppy/osu/releases/tag/2024.731.0)|
|:-:|:-:|
|![image](https://github.com/user-attachments/assets/32549f12-e3d8-4168-af8c-48410856da33)|![image](https://github.com/user-attachments/assets/467ac154-a6a7-4f09-bde5-2a3fbac62075)|

Chat timestamps are displayed differently. Awaiting feedback from other groupmembers...
