### ISSUE TITLE
Fix beatmap information text layout in Board view

### ISSUE THREAD

**Issue by CloneWith** [CloneWith/osu#6]
- [x] Determine the metadata to display
- [x] Determine the order and format
- [x] Use proper methods to arrange them

**Comment by NaughtyChas** [comment]
> * [ ] Use proper methods to arrange them

Added these lines of code in `osu.Game.Tournament/Components/BoardBeatmapPanel.cs`, in commit [972ba2b](https://github.com/CloneWith/osu/commit/972ba2bf737d149b3fe8c5280709503e9faf384e) on branch [derived/tboard_ntcsAppend](https://github.com/CloneWith/osu/compare/derived/tboard_ntcsAppend):

```Csharp
                                {
                                    Text = Beatmap?.Metadata.Author.Username ?? "unknown",
                                    Font = OsuFont.Torus.With(weight: FontWeight.Bold, size: 14),
                                    MaxWidth = 79, // Added
                                    Margin = new MarginPadding { Right = 20 }, // Adjusts the space to the right of the mapper name
                                },

// @@ -140,6 +141,7 @@ private void load(LadderInfo ladder)

                                new TournamentSpriteText
                                {
                                    Text = Beatmap?.DifficultyName ?? "unknown",
                                    MaxWidth = 75, //Added
                                    Font = OsuFont.Torus.With(weight: FontWeight.Bold, size: 14),
                                },
                            }

```

---

`MaxWidth = <value>,` is added to the code for mapper/difficulty name warp. However this will cause alignment issue in beatmap title: 

![image](https://github.com/user-attachments/assets/0b70914f-eab7-451a-a770-ce5af4554b65)

Looking for another fix.

**Comment by NaughtyChas** [comment]
Nice solution on commit [f28cc32](https://github.com/CloneWith/osu/commit/f28cc326ff73f58edcd5ffb7d3bf562bf5dbdbe7) pushed onto branch [derived/tboard](https://github.com/CloneWith/osu/compare/derived/tboard). Now the beatmap imformation will not exceed the boundary however beatmap titles are not displayed in the same height:

![image](https://github.com/user-attachments/assets/6105f5f3-65a5-40bd-bc10-9627b438176e)

**Comment by CloneWith** [comment]
I've just changed the anchor & origin of the parent `FillFlowContainer` to `TopLeft`, which will make the text sprite locate at a fixed point and align properly. For details see [this commit](https://github.com/CloneWith/osu/commit/f12e6397af30892d6f0d81b79e98d34a5097e059).

![Board view with adjusted anchor and origin](https://github.com/user-attachments/assets/f11e5244-3293-431b-bbb9-3209ec8aa17b)

**Comment by NaughtyChas** [comment]
> I've just changed the anchor & origin of the parent `FillFlowContainer` to `TopLeft`, which will make the text sprite locate at a fixed point and align properly. For details see [this commit](https://github.com/CloneWith/osu/commit/f12e6397af30892d6f0d81b79e98d34a5097e059).
> 
> ![Board view with adjusted anchor and origin](https://private-user-images.githubusercontent.com/110881926/353662368-f11e5244-3293-431b-bbb9-3209ec8aa17b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTExMDYsIm5iZiI6MTcyMjM5MDgwNiwicGF0aCI6Ii8xMTA4ODE5MjYvMzUzNjYyMzY4LWYxMWU1MjQ0LTMyOTMtNDMxYi1iYmI5LTMyMDllYzhhYTE3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwMTUzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjQ2ODBhZDFmMmNlNzdhZjllOWI5ZjViNDAyMmRmNDI4NTg0Y2EyZTEzNTJhYjdiZjYzYTM0OWU1ZmYwZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gUG5nucJw6BarngIO5r54mgFTvZ_KV6-_a-8SKc9PYY)

Reviewed, works fine in English display too. Cheers on your fantastic work!

![image](https://github.com/user-attachments/assets/ad9d4b65-ceae-4c31-abbd-0ece7b8aa7c5)

Closing this issue as complete now.
